name: Publis-Tests

on: [push]

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publis-Tests
      uses: Cschau0701vip/Publis-Tests@main
      with:
        artifacts_path: './'
    
