name: Publis-Tests

on: pull_request

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publis-Tests
      uses: Cschau0701vip/Publis-Tests@main
      with:
        artifacts_path: './results/**/*TEST-*.xml'
        pull_request_number: ${{ github.event.number }}
        gh_token: ${{ secrets.GH_TOKEN }}
        gh_repo: ${{ github.repository }}
        
