name: Generate Chart

on: pull_request

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
        npm install

    - name: Generate HTML
      run: python publish-tests-results.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: chart
        path: test-summary.html
